paths:
  /api/user/pathway/protein/mock:
    post:
      summary: Create mock pathways for the authenticated user
      tags: [TestMuck]
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numberOfPathways:
                  type: integer
                  minimum: 1
                  maximum: 500
                  example: 10
              required:
                - numberOfPathways
      responses:
        201:
          description: Pathway created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        500:
          description: Internal server error
