paths:
  /api/user/pathway/protein/{id}:
    get:
      summary: Get a single pathway by ID
      tags: [UserPathway]
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the pathway to retrieve
      responses:
        200:
          description: Pathway details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pathway"
        401:
          description: Unauthorized
        404:
          description: Pathway not found
