paths:
  /api/auth/forgot-password:
    post:
      summary: Send a password reset email
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPasswordDTO"
      responses:
        200:
          description: Password reset email sent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        400:
          description: Bad request
