paths:
  /api/auth/login:
    post:
      summary: User login
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDTO"
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
          headers:
            Set-Cookie:
              description: HttpOnly cookie containing the access token
              schema:
                type: string
                example: accessToken=abc123; HttpOnly; Secure
        400:
          description: Invalid credentials
