paths:
  /api/auth/update-password:
    patch:
      summary: Update password for authenticated user
      tags: [Auth]
      security:
        - cookieAuthAccess: []
        - cookieAuthRefresh: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePasswordDTO"
      responses:
        200:
          description: Password updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        400:
          description: Bad request
        401:
          description: Unauthorized
